### PR TITLE
Broken link to test/README.md

### PR DESCRIPTION
**Pull request by piermarcobarbe**
The link returned 404 Error.
I think this is the correct URL.

**Description**
Hitting the older link gave me a 404 Error.

**Purpose**
Update the URL for that link. The proposed URL is the one i could refer manually.

### CODE REVIEW

**Comment by piermarcobarbe** [comment]
@googlebot I signed it!

**Comment by samdutton** [comment]
Thanks for this! Appreciate it. Just checking CLA stuff before merging.

**Comment by samdutton** [comment]
Thanks for this! Appreciate it. Just checking CLA stuff before merging.

**Comment by piermarcobarbe** [comment]
@googlebot  I signed it!

**Comment by piermarcobarbe** [comment]
> Thanks for this!
> 
> For some reason the CLA check is still failing.
> 
> I can see that you've signed the CLA, but could you [verify that your email is set on your git commits](https://help.github.com/en/articles/setting-your-commit-email-address)?

Yup, I had to change my primary email address.

**Comment by samdutton** [comment]
Thank you.

**Comment by fippo** [comment]
This repo is a (supposedly) read-only fork of https://github.com/webrtchacks/adapter these days. I  [adapted the fix](https://github.com/webrtcHacks/adapter/commit/7473160a8110ccb7a6ffd8a281c09facdf3f2e59) and force-pushed here so repos don't diverge.

@alvestrand (or maybe @samdutton can too): can you disable issues and PRs on this repositry please?

**Comment by samdutton** [comment]
Thanks for sorting this @fippo! 

Issues are disabled for this repo. I don't think we can disable PRs (can we?) but we can certainly avoid accepting PRs in future: https://github.com/dear-github/dear-github/issues/84.

**Pull request merged**
